development:
  adapter: postgresql
  encoding: unicode
  database: nycstuntpros_development
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV["postgres_pass"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: nycstuntpros_test
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV["postgres_pass"] %>

production:
  adapter: postgresql
  encoding: unicode
  database: nycstuntpros_production
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV["postgres_pass"] %>
