require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there instance very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StuntProfilesController do

  # This should return the minimal set of attributes required to create a valid
  # StuntProfile. As you add validations to StuntProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StuntProfilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stunt_profiles as @stunt_profiles" do
      stunt_profile = StuntProfile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stunt_profiles).should eq([stunt_profile])
    end
  end

  describe "GET show" do
    it "assigns the requested stunt_profile as @stunt_profile" do
      stunt_profile = StuntProfile.create! valid_attributes
      get :show, {:id => stunt_profile.to_param}, valid_session
      assigns(:stunt_profile).should eq(stunt_profile)
    end
  end

  describe "GET new" do
    it "assigns a new stunt_profile as @stunt_profile" do
      get :new, {}, valid_session
      assigns(:stunt_profile).should be_a_new(StuntProfile)
    end
  end

  describe "GET edit" do
    it "assigns the requested stunt_profile as @stunt_profile" do
      stunt_profile = StuntProfile.create! valid_attributes
      get :edit, {:id => stunt_profile.to_param}, valid_session
      assigns(:stunt_profile).should eq(stunt_profile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StuntProfile" do
        expect {
          post :create, {:stunt_profile => valid_attributes}, valid_session
        }.to change(StuntProfile, :count).by(1)
      end

      it "assigns a newly created stunt_profile as @stunt_profile" do
        post :create, {:stunt_profile => valid_attributes}, valid_session
        assigns(:stunt_profile).should be_a(StuntProfile)
        assigns(:stunt_profile).should be_persisted
      end

      it "redirects to the created stunt_profile" do
        post :create, {:stunt_profile => valid_attributes}, valid_session
        response.should redirect_to(StuntProfile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stunt_profile as @stunt_profile" do
        # Trigger the behavior that occurs when invalid params are submitted
        StuntProfile.any_instance.stub(:save).and_return(false)
        post :create, {:stunt_profile => { "user_id" => "invalid value" }}, valid_session
        assigns(:stunt_profile).should be_a_new(StuntProfile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StuntProfile.any_instance.stub(:save).and_return(false)
        post :create, {:stunt_profile => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stunt_profile" do
        stunt_profile = StuntProfile.create! valid_attributes
        # Assuming there are no other stunt_profiles in the database, this
        # specifies that the StuntProfile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StuntProfile.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => stunt_profile.to_param, :stunt_profile => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested stunt_profile as @stunt_profile" do
        stunt_profile = StuntProfile.create! valid_attributes
        put :update, {:id => stunt_profile.to_param, :stunt_profile => valid_attributes}, valid_session
        assigns(:stunt_profile).should eq(stunt_profile)
      end

      it "redirects to the stunt_profile" do
        stunt_profile = StuntProfile.create! valid_attributes
        put :update, {:id => stunt_profile.to_param, :stunt_profile => valid_attributes}, valid_session
        response.should redirect_to(stunt_profile)
      end
    end

    describe "with invalid params" do
      it "assigns the stunt_profile as @stunt_profile" do
        stunt_profile = StuntProfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StuntProfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => stunt_profile.to_param, :stunt_profile => { "user_id" => "invalid value" }}, valid_session
        assigns(:stunt_profile).should eq(stunt_profile)
      end

      it "re-renders the 'edit' template" do
        stunt_profile = StuntProfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StuntProfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => stunt_profile.to_param, :stunt_profile => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stunt_profile" do
      stunt_profile = StuntProfile.create! valid_attributes
      expect {
        delete :destroy, {:id => stunt_profile.to_param}, valid_session
      }.to change(StuntProfile, :count).by(-1)
    end

    it "redirects to the stunt_profiles list" do
      stunt_profile = StuntProfile.create! valid_attributes
      delete :destroy, {:id => stunt_profile.to_param}, valid_session
      response.should redirect_to(stunt_profiles_url)
    end
  end

end
